#!/usr/bin/env python
# Simple 3min and 15seconds timer program for feeding mags

import time
from playsound import playsound #these events block others from occuring at the same time.
from subprocess import call

sec = 193
while sec > 0:
    
    if sec == 193:
        playsound('C:/Users/kamik/code/projects/mag_timer/sounds/AlpineCheckPoint.wav') # Sound file plays for 2 seconds
    if sec == 30:
        print("30 seconds to go...get ready to\n------------------------\nF   E   E   D     M   E\n------------------------") 
    if sec == 1:
        playsound('C:/Users/kamik/code/projects/mag_timer/sounds/rose_confession.mp3') # sound file plays for 25 seconds
        call('clear')
        sec = 194 # Reset timer to 3 minutes and 14 seconds

    time.sleep(1) # every second
    sec -= 1 # take one second away
